name: Build & Publish

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
        default: latest
        description: minecraft version to build
      channel:
        required: false
        type: string
        default: release
        description: release or snapshot

  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: latest
        description: minecraft version to build
      channel:
        required: false
        type: string
        default: release
        description: release or snapshot
    secrets:
      MODRINTH_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip

      - run: pip install -r requirements.txt
      - run: python src/main.py -c ${{ inputs.channel }} -v ${{ inputs.version }}

      - name: Set Vars
        uses: actions/github-script@v7
        with:
          script: |
            const {readFileSync}  = require("fs");
            const versions = readFileSync("build/supported-versions.txt", "utf8").trim().split("\n");
            core.exportVariable("max_version", versions.at(0));
            core.exportVariable("code_version", readFileSync("version.txt", "utf8").trim());
            core.exportVariable("game_version", readFileSync("build/supported-versions.txt", "utf8").trim());

      - uses: cloudnode-pro/modrinth-publish@v2
        with:
          project: tVUawz1v
          loaders: datapack
          name: v${{ env.code_version }} for ${{ env.max_version }}
          version: ${{ env.code_version }}+mc${{ env.max_version }}
          game-versions: ${{ env.game_version }}
          files: build/getblock-${{ env.code_version }}+mc${{ env.max_version }}.zip
          token: ${{ secrets.MODRINTH_TOKEN }}
